### PR TITLE
fix(pre): adjust image optimization

### LINKED ISSUE #657: Breaking March: <picture> default behaviour
it would be great to introduce responsive images in helix pages by default.

while there may be a broad range of configuration options, we can get to a place that is a significant improvement over the current behavior by changing the current img tag from eg:

```
            <img src="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png">
```

to 

```
<picture>
            <source media="(max-width: 400px)" srcset="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png?width=750&format=webply&optimize=medium" />
            <img loading="lazy" src="/hlx_dd76df9c9b121fec5f1b6bc39481247a1f756139.png?width=2000&format=webply&optimize=medium" alt=""/>
</picture>
```

with the first img set to `loading="eager"`

### PR DESCRIPTION
**Pull request by tripodsan**
see latest spec in #657

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -74,9 +69,30 @@ function toClassName(text) {
...
 
+/**
+ * Adds the fastly-image-optimization url params to the given image src.
+ * @param {string} src The image source.
+ * @param {number} [width = 0] optional 'width' parameter
+ * @param {string} [format = 'webply'] image format.
+ * @param {string} [optimize = 'medium'] optimization.
+ * @returns {string}
+ */
+function optimizeImageURL(src, width, format = 'webply', optimize = 'medium') {
```
Comment (rofe) [inline src/utils.js:80]: Should we go for a `optimizeImageURL(src, options)` signature instead to allow overriding just a single param and for future extensions?

**Review by rofe — APPROVED** [review]

File: src/utils.js (hunk 1 above)
Comment (tripodsan) [reply src/utils.js:80]: hmm... I thought about it, and I thought it's overkill. we can still add it, if we need it.
