### PR TITLE
fix(sidekick): byocdn flag always set on update

### LINKED ISSUE #885: Sidekick: bookmarklet updater always sets byocdn to true
During the last sidekick update, all bookmarklet configs have been patched with the `byocdn` flag set, regardless whether their project's production CDN is Fastly or not. This leads to publishing problems in all projects that don't bring their own CDN.

### PR DESCRIPTION
**Pull request by rofe**
Fix #885

### CODE REVIEW

File: tools/sidekick/app.js [hunk 1]
```diff
@@ -323,11 +323,19 @@
    * @param {Sidekick} sk The sidekick
    */
   function checkForUpdates(sk) {
+    // check for wrong byocdn config
+    // https://github.com/adobe/helix-pages/issues/885
+    if (sk.config.byocdn && !/^www.*\.adobe\.com$/.test(sk.config.host)) {
```
Comment (kptdobe) [inline tools/sidekick/app.js:328]: Do we really need to hardcode www.adobe.com here ?

**Review by kptdobe — APPROVED** [review]

File: tools/sidekick/app.js (hunk 1 above)
Comment (rofe) [reply tools/sidekick/app.js:328]: If we want to auto-heal user configs, yes. All `*adobe.com` prod hosts except `www*.adobe.com` are affected. I;m open to better solutions!
